//var who = 'world';function sayhello65() {alert('Hello, ' + who + '!');}
//function taro65() {who = '太郎';}
//function hanako65() {who = '花子';}
//function sayhello65() {var who='world';alert('Hello,' + who + '!');}
//function taro65() {who = '太郎';}
//function hanako65() {who = '花子';}
var who = 'world';function sayhello65() {alert('Hello, ' + who + '!');}
function taro65()  {who ='太郎';alert(who+'が来た');}
function hanako65()  {who ='花子';alert(who+'が来た');}