//var who = 'world';function sayhello() {alert('Hello, ' + who + '!');}
//function taro() {who = '太郎';}
//function hanako() {who = '花子';}
//function sayhello() {var who='world';alert('Hello,' + who + '!');}
//function taro() {who = '太郎';}
//function hanako() {who = '花子';}
var who = 'world';function sayhello65() {alert('Hello, ' + who + '!');}
var who = '太郎';function taro65()  {alert('太郎が来た');}
var who = '花子';function hanako65()  {alert('花子が来た');}